# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["peijin8917"] %>
  email_provider_password: <%= ENV["52tchu52liang"] %>
  mailchimp_api_key: <%= ENV["89bcfdfb633877b4f8a12d7881f69faa-us11"] %>
  mailchimp_list_id: <%= ENV["13e89277cd"] %>
  domain_name: example.com
  owner_email: <%= ENV["peijin8917@gmail.com"] %>

test:
  secret_key_base: e72ff0a178b3b74a799ef4385c7c1a3efaa67821369acfb776ee3f64fe2d8083219106700c3229f7ffc30b527e6c2ca5614ec068d319f3e2368c3d4d5dc5e54e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
